# Generated by Django 4.2.1 on 2023-11-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword1', models.CharField(max_length=20, verbose_name='关键词1')),
                ('Keyword2', models.CharField(max_length=20, verbose_name='关键词2')),
                ('Keyword3', models.CharField(max_length=20, verbose_name='关键词3')),
                ('Keyword4', models.CharField(max_length=20, verbose_name='关键词4')),
                ('Keyword5', models.CharField(max_length=20, verbose_name='关键词5')),
                ('Keyword6', models.CharField(max_length=20, verbose_name='关键词6')),
                ('Keyword7', models.CharField(max_length=20, verbose_name='关键词7')),
                ('Keyword8', models.CharField(max_length=20, verbose_name='关键词8')),
            ],
        ),
    ]
